### PR TITLE
added ZigOps PaymentProcessor Microservice

### PR DESCRIPTION
**Pull request by ZwelithiniMphanza**
Hey Thulani just added the ZigOps Payment Processing Microservice

### CODE REVIEW

**Comment by OlivierJM** [comment]
I understand there is no licence attached to the repo but I was wondering if this is meant to be publicly available and opensource

**Comment by thulani196** [comment]
It is meant to be public, only temporarily though. Everything will be deleted

**Comment by OlivierJM** [comment]
> It is meant to be public, only temporarily though. Everything will be deleted

Makes sense.

**Comment by thulani196** [comment]
I might as well make it private and just invite the intended audience to see. Good thought, @OlivierJM

**Comment by OlivierJM** [comment]
That is what I would advise you do, considering that all the code added here is very proprietary.

**Pull request merged**
